language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn test
  - yarn semantic-release-pre
  - yarn build
after_success:
  - yarn publish-npm
  - yarn semantic-release-post
branches:
  only:
    - master